spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
  jpa:
    show-sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  config:
    import: optional:classpath:secret.properties

app:
  storage:
    location: uploads

