spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:/uploads/

app:
  storage:
    location: C:/uploads

