spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipes
    username: root
    password: wpiszHaslo
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:/uploads/
app:
  storage:
    location: C:/uploads
