spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:/uploads/
  mail:
    password:
      ${EMAIL_PASSWORD}
app:
  storage:
    location: C:/uploads

