spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml

  security:
    oauth2:
      client:
        registration:
          google:
            scope: email, profile


  mail:
    host:
      smtp.gmail.com
    port: 587
    username: kuchniabartosza@gmail.com
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true

