spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:/uploads/
  mail:
    password:
      ${EMAIL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

app:
  storage:
    location: C:/uploads

