spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: yourClientId
            client-secret: yourClientSecret
            scope: email, profile

